
@Library('java-jenkins-shared-lib') _
mavenDockerPropDeployTemplate(propBranch: 'master', scmPropUrl: 'https://github.com/sujnanarai/jenkins-pipeline-util.git',						
						gitCredentialsId: 'GIT_CREDENTIAL')

    


