
node {
  
@Library('java-jenkins-shared-lib') _

def props = readProperties  file: 'java-spring-boot-contacts/build.properties'
print props['pom.path']
/*
mavenDockerDeployTemplate(branch: 'release-docker', scmUrl: 'https://github.com/sujnanarai/java-spring-boot-contacts.git',
						projectPath: 'spring-boot-contacts/',
						gitCredentialsId: 'GIT_CREDENTIAL', dockerCredentialsId: 'DOCKER_HUB_CRED',
						dockerImageName: 'sujnanarai/spring-boot-contacts', dockerImageVersion:'1.0.2',
						ec2CredentialsId: 'EC2_CREDENTIAL', ec2Host: '35.154.145.92', ec2UserId: 'ec2-user',
						dockerPort: '8080', webPort: '8080',
						isPostmanScripts: true,
						toEmailList: 'sujnana.rai@mindtree.com; sujnanarai@gmail.com')*/
}